# Generated by Django 4.2.25 on 2025-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='surface_type',
            field=models.CharField(choices=[('clay', 'Clay'), ('hard', 'Hard')], default='hard', max_length=10),
        ),
    ]
