# Generated by Django 4.2.25 on 2025-10-06 11:49

from django.db import migrations, models
from booking.models import Court

def create_courts(apps, schema_editor):
    Court = apps.get_model('booking', 'Court')
    
    courts = [
        # Indoor Hard Courts
        *[Court(name=f"Indoor Court {i+1}", court_type='indoor', surface_type='hard') for i in range(6)],
        
        # Outdoor Hard Courts
        *[Court(name=f"Outdoor Hard Court {i+1}", court_type='outdoor', surface_type='hard') for i in range(4)],
        
        # Outdoor Clay Courts
        *[Court(name=f"Outdoor Clay Court {i+1}", court_type='outdoor', surface_type='clay') for i in range(4)],
    ]
    Court.objects.bulk_create(courts)
    print("Courts created:", Court.objects.count())


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]


    operations = [
        migrations.AddField(
            model_name='court',
            name='surface_type',
            field=models.CharField(choices=[('clay', 'Clay'), ('hard', 'Hard')], default='hard', max_length=10),
        ),
        migrations.RunPython(create_courts),
    ]
